version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=backend.app
      - FLASK_DEBUG=1
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    networks:
      - talentvibe-network
    restart: unless-stopped
    command: ["python", "-m", "backend"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - talentvibe-network
    restart: unless-stopped
    command: ["npm", "start"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - talentvibe-network
    restart: unless-stopped

volumes:
  backend_data:
  redis_data:

networks:
  talentvibe-network:
    driver: bridge 